name: Android Build

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App name (project name)'
        required: true
        default: 'GeneratedApp'
      package_name:
        description: 'Android package name'
        required: true
        default: 'com.example.generatedapp'
      prompt:
        description: 'UI/feature prompt (vi/en)'
        required: true
        default: 'Màn hình danh sách đơn giản với Material3'

permissions:
  contents: read

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install generator deps (minimal)
        run: |
          python -m pip install -U pip
          pip install -r backend/requirements-min.txt

      - name: Generate Android project zip
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Determine inputs or use defaults when empty (push event)
          APP_NAME="${{ github.event.inputs.app_name }}"; [ -z "$APP_NAME" ] && APP_NAME="GeneratedApp"
          PKG_NAME="${{ github.event.inputs.package_name }}"; [ -z "$PKG_NAME" ] && PKG_NAME="com.example.generatedapp"
          PROMPT_TEXT="${{ github.event.inputs.prompt }}"; [ -z "$PROMPT_TEXT" ] && PROMPT_TEXT="Màn hình danh sách đơn giản với Material3"
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV
          echo "PROMPT_TEXT=$PROMPT_TEXT" >> $GITHUB_ENV
          if [ -n "${GEMINI_API_KEY:-}" ]; then
            export LLM_PROVIDER=gemini
          fi
          python -m backend.cli \
            -n "$APP_NAME" \
            -p "$PKG_NAME" \
            -r "$PROMPT_TEXT" \
            -o android-project.zip

      - name: Unzip generated project
        run: |
          rm -rf generated && mkdir -p generated
          unzip -q android-project.zip -d generated

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" --sdk_root="$ANDROID_SDK_ROOT"
          yes | sdkmanager --licenses --sdk_root="$ANDROID_SDK_ROOT"

      - name: Initialize Gradle wrapper (8.7)
        run: |
          cd generated
          gradle -v
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew

      - name: Build with retry/fix loop
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          APP_NAME: ${{ env.APP_NAME }}
          PKG_NAME: ${{ env.PKG_NAME }}
          PROMPT_TEXT: ${{ env.PROMPT_TEXT }}
        run: |
          bash .github/scripts/build_android.sh generated

      - name: Upload APK/AAB artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: |
            generated/app/build/outputs/apk/**
            generated/app/build/outputs/bundle/**
            android-project.zip
          if-no-files-found: warn

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build-logs/